# Rendered and committed by .github/workflows/manfests-scan-push.yml.
# This file deliberately contains image locations and immutable tags only.
images:
  api:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-api
    tag: sha-d6fd5a559bdfc076b4e0b03f0266603add096bb8
  orchestrator:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-orchestrator
    tag: sha-d6fd5a559bdfc076b4e0b03f0266603add096bb8
  retriever:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-retriever
    tag: sha-d6fd5a559bdfc076b4e0b03f0266603add096bb8
  answer:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-answer
    tag: sha-d6fd5a559bdfc076b4e0b03f0266603add096bb8

ingress:
  enabled: true
  className: alb
  hostname: 5hort.site
  tls:
    enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: 5hort.site
