# Rendered and committed by .github/workflows/manfests-scan-push.yml.
# This file deliberately contains image locations and immutable tags only.
images:
  api:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-api
    tag: sha-2d42bd7e8550880932c8f08a0136d2b82048802f
  orchestrator:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-orchestrator
    tag: sha-fa062c927d9472b756d20e1d09702cbd31515ccf
  retriever:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-retriever
    tag: sha-2d42bd7e8550880932c8f08a0136d2b82048802f
  answer:
    repository: 522565516627.dkr.ecr.eu-west-2.amazonaws.com/kubemind-answer
    tag: sha-ea0d904b6b2f8ef37fb9be5c8b60ea8f24b00c6f

ingress:
  enabled: true
  className: alb
  hostname: 5hort.site
  tls:
    enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: 5hort.site
