{{- if .Values.agentServices.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubemind.fullname" . }}
  labels:
    {{- include "kubemind.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
